/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userValidation = require('./user.validation');
/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.authValidation = require('./auth.validation');
