/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { FaceBookUser } from 'models';
import { userService } from 'services';

export async function getFaceBookUserById(id, options = {}) {
    const faceBookUser = await FaceBookUser.findById(id, options.projection, options);
    return faceBookUser;
}

export async function getFaceBookUserOne(query, options = {}) {
    const faceBookUser = await FaceBookUser.findOne(query, options.projection, options);
    return faceBookUser;
}

export async function getUserFriendListWithPagination(filter, options = {}) {
    const faceBookUser = await FaceBookUser.paginate(filter, options);
    return faceBookUser;
}

export async function updatefaceBookUser(filter, body, options = {}) {
    const userData = await userService.getOne(filter, {});
    if (!userData) {
        throw new ApiError(httpStatus.NOT_FOUND, 'user not found');
    }
    const faceBookUser = await FaceBookUser.findOneAndUpdate(filter, body, options);
    return faceBookUser;
}

export async function faceBookUserAggregatePaginate(paginate) {
    const options = {
        page: paginate?.offset || 1,
        limit: paginate?.limit || 100
    };
    
    // Create the aggregation pipeline once
    const aggregate = FaceBookUser.aggregate(paginate?.query || []);
    
    // Use aggregatePaginate with the aggregation pipeline and options
    const faceBookUser = await FaceBookUser.aggregatePaginate(aggregate, options);
    
    return faceBookUser;
}

