/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from 'utils/ApiError';
import httpStatus from 'http-status';
import { FriendRequest, User } from 'models';

export async function createRequest(body) {
  const request = await FriendRequest.create(body);
  return request;
}

export async function findRequest(body) {
  const existingRequest = await FriendRequest.findOne(body);
  if (!existingRequest) {
    throw new ApiError(httpStatus.NOT_FOUND, 'Friend request not found.');
  }

  return existingRequest;
}

export async function getOne(query, options = {}) {
  const record = await FriendRequest.findOne(
    query,
    options.projection,
    options
  );
  return record;
}

export async function checkExistingRequest(body) {
  const existingRequest = await FriendRequest.findOne(body);
  // if (existingRequest)
  //   throw new ApiError(httpStatus.NOT_FOUND, 'Friend request already sent.');
  return existingRequest;
}

export async function getFriendRequestListWithPagination(query, options = {}) {
  const requestList = await FriendRequest.find(query)
    .limit(options.limit * 1)
    .skip((options.page - 1) * options.limit)
    .exec();

  return requestList;
}

export async function getFriendListWithPagination(query, options = {}) {
  console.log(query);
  const requestList = await User.find(query)
    .select('friends')
    .populate({
      path: 'friends',
      select: 'name email',
      options: {
        limit: options.limit * 1,
        skip: (options.page - 1) * options.limit,
      },
    })
    .exec();

  return requestList;
}

export async function updateRequest(filter, body, options = {}) {
  const requestData = await getOne(filter, {});
  console.log('requestData', requestData);
  if (!requestData) {
    throw new ApiError(httpStatus.NOT_FOUND, 'request not found');
  }

  const user = await FriendRequest.findOneAndUpdate(filter, body, options);
  return user;
}
