/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.userService = require('./user.service');
module.exports.authService = require('./auth.service');
module.exports.tokenService = require('./token.service');
module.exports.fbRequestService = require('./fb-request.service');
