/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 * Only fields name will be overwritten, if the field name will be changed.
 */
import ApiError from "utils/ApiError";
import httpStatus from "http-status";
import { User, Request } from "models";
import { log } from "console";

export async function getAllfriends(id) {
  console.log(id);
  const user = await User.findById(id).populate("friends");
  if (user.friends.length !== 0) {
    return user.friends;
  } else {
    return null;
  }
}

export async function getAllRequest(id, skip, limit) {
  const requests = await Request.find({ to: id })
    .skip(skip)
    .limit(limit)
    .exec();
  return requests;
}

export async function createRequest(body) {
  if (await isRequestSend(body.from, body.to)) {
    throw new ApiError(httpStatus.BAD_REQUEST, "Request is already send");
  }
  const request = await Request.create({ ...body, accepted: false });
  return request;
}

async function isRequestSend(from, to) {
  const request = await Request.findOne({ from, to });
  return !!request;
}

export async function updateRequest(body) {
  const reqest = await Request.findOneAndUpdate(
    { _id: body.requestId },
    { $set: { aaccepted: body.accepted } }
  );

  console.log("updated req", reqest);

  const user = await User.findOne({ _id: reqest.to });
  console.log(user.friends);

  const friend = user.friends.find((id) => id === reqest.from);

  if (!friend) {
    await User.findOneAndUpdate(
      { _id: reqest.to },
      { $push: { friends: reqest.from } }
    );
  }
  console.log("user up", user);

  return reqest;
}
