/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
const EnumCodeTypeOfCode = {
  RESETPASSWORD: 'resetPassword',
  LOGIN: 'login',
};
const EnumRoleOfUser = {
  USER: 'user',
};
const EnumTypeOfToken = {
  RESET_PASSWORD: 'resetPassword',
  VERIFY_EMAIL: 'verifyEmail',
  REFRESH: 'refresh',
};
/**
 * Lifecycle states of a friend request.
 */
const EnumFriendRequestStatus = {
  PENDING: 'pending',
  ACCEPTED: 'accepted',
  REJECTED: 'rejected',
};
module.exports = {
  EnumCodeTypeOfCode,
  EnumRoleOfUser,
  EnumTypeOfToken,
  EnumFriendRequestStatus,
};
