/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
import mongoose from 'mongoose';
import { toJSON } from './plugins';

const friendsReqSchema = mongoose.Schema(
  {
    senderID: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    receiverID: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    status: {
      type: String,
      default: "Pending",
      required: true,
    }
  },
  {
    timestamps: true,
  }
);
// add plugin that converts mongoose to json
friendsReqSchema.plugin(toJSON);
/**
 * @typedef FriendsReq
 */
const FriendsReq = mongoose.models.FriendsReq || mongoose.model('FriendsReq', friendsReqSchema);
module.exports = FriendsReq;
