/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
module.exports.User = require('./user.model');
module.exports.Token = require('./token.model');
module.exports.Enum = require('./enum.model');
module.exports.plugins = require('./plugins');
