/**
 * This file is generated by Appinvento, also it can be overwritten by Appinvento.
 */
import mongoose from 'mongoose';
import { toJSON } from './plugins';
import mongoosePaginateV2 from 'mongoose-paginate-v2';
// import enumModel from './enum.model';

const friendRequestSchema = mongoose.Schema(
  {
    requester: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    status: {
      type: String,
      enum: ['pending', 'accepted', 'rejected'],
      default: 'pending',
    },
    /*type: {
      type: String,
      enum: Object.values(enumModel.EnumTypeOfToken),
      required: true,
    }*/
  },
  {
    timestamps: true,
  }
);
// add plugin that converts mongoose to json
friendRequestSchema.plugin(toJSON);
friendRequestSchema.plugin(mongoosePaginateV2);
/**
 * @typedef FriendRequest
 */
const FriendRequest =
  mongoose.models.FriendRequest ||
  mongoose.model('FriendRequest', friendRequestSchema);
module.exports = FriendRequest;
